name: GoldBot Scheduler

on:
  schedule:
    - cron: '30 5 * * *'    # 09:00 ایران
    - cron: '30 10 * * *'   # 14:00 ایران
    - cron: '30 15 * * *'   # 19:00 ایران
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run RTL debug
        run: python debug_font_rtl.py


      - name: Run Telegram Bot
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: |
          python bot.py
